# Stage 1: Build the frontend app
FROM node:22 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the package.json
COPY ./frontend/package.json ./

# Install dependencies
RUN npm install

# Copy the frontend files into the container
COPY ./frontend .

# Copy the .env file from the root directory into the /app directory
COPY .env /app/.env

# Build the Vite app (static files will be generated in the 'dist' folder)
RUN npm run build

# Remove the .env file after the build
RUN rm -f /app/.env

# Stage 2: Serve the built app with Caddy
FROM caddy:alpine

# Copy the built files from to the Caddy server
COPY --from=build /app/dist /usr/share/caddy

# Copy the Caddyfile to the Caddy server
COPY ./frontend/Caddyfile /etc/caddy