services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: errand_planner
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_KEY_TTL: ${REDIS_KEY_TTL}
      REDIS_HOST: redis
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - postgres
      - redis
    command:
      [
        "/bin/bash",
        "-c",
        "/app/wait-for-it.sh postgres:${POSTGRES_PORT} -- /app/wait-for-it.sh redis:${REDIS_PORT} -- npm start",
      ]

# Ensures that the volumes persist data across container restarts
volumes:
  postgres_data:
  redis_data:
