services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: errand_planner
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - postgres
    command:
      [
        "/bin/bash",
        "-c",
        "/app/wait-for-it.sh postgres:${POSTGRES_PORT} -- npm start",
      ]

# Ensures that the volumes persist data across container restarts
volumes:
  postgres_data:
