# Use an official Node.js runtime as a parent image
FROM node:22

# Set the working directory in the container
WORKDIR /app

# Copy the package.json
COPY package.json ./

# Copy the package-lock.json
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Expose the port that the app will run on
EXPOSE 3000

# Start the Express app
CMD ["npm", "start"]